# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface:
                    algorithm: sha512
                    iterations: 1000

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_USER:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
            chain_provider:
                chain:
                    providers: [fos_userbundle, in_memory]
            fos_userbundle:
                id: fos_user.user_provider.username
            in_memory:
                memory:
                    users:
                        user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                        admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
            dev:
                pattern:  ^/(_(profiler|wdt)|css|images|js|fonts)/
                security: false
            secured_area:
                pattern: ^/
                form_login:
                    provider: chain_provider
                    csrf_provider: form.csrf_provider
                logout: ~
                anonymous: ~
                http_basic: ~

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

            - { path: ^/empresa/*, role: ROLE_ADMIN }
            - { path: ^/clasificadorticket/*, role: ROLE_ADMIN }
            - { path: ^/clasificadorprioridad/*, role: ROLE_ADMIN }
            - { path: ^/clasificadorestado/*, role: ROLE_ADMIN }
            - { path: ^/clasificadoretapa/*, role: ROLE_ADMIN }

            - { path: ^/proyecto/new, role: ROLE_ADMIN }
            - { path: ^/proyecto/edit/*, role: ROLE_ADMIN }
            - { path: ^/proyecto/*, role: ROLE_ADMIN, methods: [DELETE, PUT] }
            - { path: ^/proyectos/ , role: ROLE_USER }

            - { path: ^/security/, role: ROLE_SUPER_ADMIN }
            - { path: ^/, role: ROLE_USER }

