<?php

namespace HatueySoft\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * clasificador_prioridadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificadorPrioridadRepository extends EntityRepository
{
}
