<?php

namespace HatueySoft\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * clasificadorTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificadorTicketRepository extends EntityRepository
{
}
