<?php

namespace HatueySoft\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClasificadorEstadoProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificadorEstadoProyectoRepository extends EntityRepository
{
}
