<?php

namespace HatueySoft\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoRepository extends EntityRepository
{
    public function getProyectosByUsuario($usuario)
    {
        $em = $this->getEntityManager();

        $repository = $em->getRepository('HatueySoftTicketBundle:Proyecto');
        $query = $repository->createQueryBuilder('p')
            ->innerJoin('p.usuarios', 'u')
            ->where('u.id = :user_id')
            ->setParameter('user_id', $usuario)
            ->getQuery()->getResult();
        return $query;

    }
}
