<?php

namespace HatueySoft\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
    public function getCantPorEstado($proyecto, $estado){

        $em = $this->getEntityManager();

        $repository = $em->getRepository('HatueySoftTicketBundle:Ticket');
        $query = $repository->createQueryBuilder('t')
            ->select('count(t.id)')
            ->where('t.proyecto = :proyecto')
            ->andWhere('t.estado = :estado')
            ->setParameter('proyecto', $proyecto)
            ->setParameter('estado', $estado)
            ->getQuery()->getSingleScalarResult();

        return $query;
    }

    public function getCantComentarios($ticket)
    {

        $em = $this->getEntityManager();

        $repository = $em->getRepository('HatueySoftTicketBundle:Comentario');
        $query = $repository->createQueryBuilder('c')
            ->select('count(c.id)')
            ->where('c.ticket = :ticket')
            ->setParameter('ticket', $ticket)
            ->getQuery()->getSingleScalarResult();

        return $query;
    }

    public function getComentarios($ticket)
    {
        $em = $this->getEntityManager();

        $reporsitory =  $em->getRepository('HatueySoftTicketBundle:Comentario');
        $query = $repository->createQueryBuilder('c')
            ->where('c.ticket = :ticket')
            ->setParameter('ticket', $ticket)
            ->getQuery();
        return $query;
    }

}
