<?php

namespace HatueySoft\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
    public function getCantAbiertos($proyecto, $estado){

        $em = $this->getEntityManager();

        $repository = $em->getRepository('HatueySoftTicketBundle:Ticket');
        $query = $repository->createQueryBuilder('t')
            ->where('t.proyecto = :proyecto')
            ->andWhere('t.estado = :estado')
            ->setParameter('proyecto', $proyecto)
            ->setParameter('estado', $estado)
            ->getQuery()->getResult();
        return $query;
    }
}
